image: gradle:jdk17-alpine

pipelines:
  pull-requests:
    '**':
      - step:
          name: Test
          script:
            - ./gradlew clean test
  branches:
    feature/HOT-42-add-bitbucket-pipeline-for-backend:
      - step:
          name: Test
          script:
            - docker-compose up -d
            - ./gradlew build
            - ./gradlew clean test
            - docker-compose down
      - step:
          name: Deploy to test
          deployment: test
          runs-on:
            - self.hosted
            - linux
          script:
            - echo "TEST111"