image: gradle:7.2.0-jdk17

pipelines:
  pull-requests:
    '**':
      - step:
          name: Test
          script:
            - ./gradlew clean test
  branches:
    feature/HOT-42-add-bitbucket-pipeline-for-backend:
      - step:
          name: Test
          script:
            - ./gradlew clean test
      - step:
          name: Deploy to test
          deployment: test
          runs-on:
            - self.hosted
            - linux
          script:
            - echo "TEST111"