image: openjdk:17

pipelines:
  pull-requests:
    '**':
      - step:
          name: Test
          script:
            - bash ./gradlew clean test
  branches:
    feature/HOT-42-add-bitbucket-pipeline-for-backend:
      - step:
          name: Test
          script:
            - bash ./gradlew clean test
      - step:
          name: Deploy to test
          deployment: test
          script:
            - echo "TEST111"