image: openjdk:17

pipelines:
  pull-requests:
    '**':
      - step:
          name: Test
          script:
            - ./gradlew clean test
  branches:
    feature/HOT-42-add-bitbucket-pipeline-for-backend:
      - step:
          name: Test
          runs-on:
            - self.hosted
            - linux
          script:
            - ./gradlew clean test