version: "3.7" #have to use it unless you upgrade docker-compose
services:
    db:
        image: postgres:14.1
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
