version: "3.7" #have to use it unless you upgrade docker-compose
services:
    web-project:
        image: nkuusik/web-project:latest
        container_name: web-project
        restart: always
        ports:
            - 8080:8080
        volumes:
            - /opt/web-project/application.properties:/app/application.properties